services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=production
      - SELENIUM_URL=http://selenium:4444/wd/hub
    ports:
      - "3002:3002"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.75"
          memory: 300M
    networks:
      - jim-network

networks:
  jim-network:
    external: true
